### ISSUE TITLE
App's size

### ISSUE THREAD

**Issue by shantanukamdi** [kehkashanF/fhc-app-temp#3]
Application size is over 100 MB. There is a folder in assets which is over 90 MB. Is it needed ?

**Comment by kehkashanF** [comment]
Since we are still in the Dev phase, let us please continue on building the functionality first. If we keep raising issues like this which will get resolved in the refactoring stage, then we will simple be beating around the bush.

As per the plan, everything of consequence in the assets folder will be minified and fetched from a server, considerably decreasing the app size. Since this was an obvious and foregone conclusion I did not find it necessary to open an issue for it.

Thanks for pointing it out anyways. Closing this issue.

**Comment by kehkashanF** [comment]
These files will be compressed and fetched from a server, which will be done at a later stage, during clean up. Closing this issue. Thanks.
